export const FETCH_WORKOUT_START = "FETCH_WORKOUT_START"
export const FETCH_WORKOUT_SUCCESS = "FETCH_WORKOUT_SUCCESS"
export const FETCH_WORKOUT_FAIL = "FETCH_WORKOUT_FAIL"

export const SAVE_WORKOUT_START = "SAVE_WORKOUT_START"
export const SAVE_WORKOUT_SUCCESS = "SAVE_WORKOUT_SUCCESS"
export const SAVE_WORKOUT_FAIL = "SAVE_WORKOUT_FAIL"